sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /piper/perception/cloud/filtered
    max_range: 1.5
    point_subsample: 1
    padding_offset: 0.02
    padding_scale: 1.0
    max_update_rate: 2.0
    filtered_cloud_topic: /piper/moveit/filtered_cloud
    ns: piper_wrist_camera