// Generated by gencpp from file piper_msgs_srvs/piper_cmdResponse.msg
// DO NOT EDIT!


#ifndef PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDRESPONSE_H
#define PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piper_msgs_srvs
{
template <class ContainerAllocator>
struct piper_cmdResponse_
{
  typedef piper_cmdResponse_<ContainerAllocator> Type;

  piper_cmdResponse_()
    : success(false)
    , message()  {
    }
  piper_cmdResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct piper_cmdResponse_

typedef ::piper_msgs_srvs::piper_cmdResponse_<std::allocator<void> > piper_cmdResponse;

typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse > piper_cmdResponsePtr;
typedef boost::shared_ptr< ::piper_msgs_srvs::piper_cmdResponse const> piper_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator1> & lhs, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator1> & lhs, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piper_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piper_msgs_srvs/piper_cmdResponse";
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应部分\n"
"bool success        # 执行是否成功\n"
"string message      # 返回消息\n"
;
  }

  static const char* value(const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct piper_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piper_msgs_srvs::piper_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIPER_MSGS_SRVS_MESSAGE_PIPER_CMDRESPONSE_H
